blank_issues_enabled: false
contact_links:
  - name:  Discusiones
    url: https://github.com/tu-usuario/bc-javaweb-sb/discussions
    about: Para preguntas generales, ideas y conversaciones usa GitHub Discussions
  - name:  Documentaci贸n
    url: https://github.com/tu-usuario/bc-javaweb-sb/tree/main/_docs
    about: Revisa la documentaci贸n antes de abrir un issue
  - name:  Spring Docs
    url: https://docs.spring.io/spring-boot/docs/current/reference/html/
    about: Documentaci贸n oficial de Spring Boot
  - name:  Docker Docs
    url: https://docs.docker.com/
    about: Documentaci贸n oficial de Docker
