services:
  # Base de datos PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: week07-db
    environment:
      POSTGRES_DB: bootcamp
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d bootcamp"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bootcamp-network

  # Aplicaci√≥n Spring Boot
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: week07-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: bootcamp
      DB_USER: dev
      DB_PASSWORD: dev123
      JWT_SECRET: dG9rZW5TZWNyZXRvTXV5TGFyZ29ZU2VndXJvUGFyYUpXVDI1NmJpdHMhIQ==
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bootcamp-network

volumes:
  postgres_data:

networks:
  bootcamp-network:
    driver: bridge
